### ISSUE TITLE
How can I tell what golang I have in my bosh release?

### ISSUE THREAD

**Issue by rosenhouse** [bosh-packages/golang-release#11]
So I'm looking through some old commits to try to determine which golang is used in which versions of my bosh release.

I found this commit: https://github.com/cloudfoundry/routing-release/commit/e78291370b6cf551aabc43c2c9b401c4809f3b00#diff-86049765a1952429282e24ebc5708900

What version of golang did it upgrade us to?

I see lots of hex.   I've tried searching this repo for the hex strings and looking at the resulting yaml files that are returned from the search.  I am confused.

**Comment by jfmyers9** [comment]
I agree that this is a problem, and is something that we could do better improving.

However, at the moment we aren't really thinking that much about `bosh-packages` and `vendor-package`. They are currently are low on our list of priorities right now, and are potentially thinking about deprecating them in favor of a more complete solution.

If you have any ideas on how to improve the experience, we are definitely open to suggestions / contributions.

**Comment by luan** [comment]
I agree with @jfmyers9, we could make this easier to find, but it's not super clean cut since different vendor packages might have different needs. We haven't yet had a chance to stop and discuss it.

For your use case, though, you can do the following:

```
git clone https://gihtub.com/cloudofundry/routing-release
cd routing-release
git submodule update --init --recursive
bosh create-release --tarball=/dev/stdout | tar xz packages/golang-1-linux.tgz -O 2>/dev/null | tar tz --wildcards './go*' 2>/dev/null
```

You should get output like: `./go1.11.1.linux-amd64.tar.gz` which tells me you're currently on 1.11.1 :)

**Comment by zachgersh** [comment]
side note here is the code for version we actually ended up with (test on xenial)

```bash
version=$(cat /tmp/release.tgz | tar -Oxz packages/golang-1-linux.tgz | tar z --list | grep -ohE "go[0-9]\.[0-9]{1,2}\.[0-9]{1,2}")
```

**Comment by shalako** [comment]
This continues to be a problem. I want to include in our release notes what version of golang we've bumped to. 

I'd like to discover that by looking at the packages dir: https://github.com/cloudfoundry/routing-release/blob/develop/packages/golang-1-linux/spec.lock and/or by looking at a commit message: https://github.com/cloudfoundry/routing-release/commit/0794cf6392abbb0c622c774abbb1e370407fece8

**Comment by dpb587-pivotal** [comment]
Backfilled notes for the past 10 releases; agreed it would be helpful to automate the release notes.

```
tick='`' ; for yml in $( find releases/ -name 'golang-*.yml' | gsort -rV ); do echo "# $( bosh int --path=/version $yml )" ; echo ; echo Dependencies: ; echo ; for pkg in $( bosh int $yml --path=/packages | grep name: | awk '{ print $2 }' | grep -v -- -test | grep -- -linux | gsort -rV ); do echo -n " * $tick$( echo "$pkg" | sed 's/-linux//')-*$tick: go" ; curl -sr 0-1048576 "https://bosh-packages-golang-release.s3.amazonaws.com/$( bosh int --path="/builds/$( bosh int --path=/packages/name=$pkg/version $yml )/blobstore_id" .final_builds/packages/$pkg/index.yml )" | tar -tzf- 2>/dev/null | grep amd64 | head -n1 | sed -E 's#.+go([0-9\.]+)\..+#\1#' ; done ; echo ; done
```

**Comment by dpb587-pivotal** [comment]
I got back to this again while looking to monitor repositories that are using `vendor-package` [to know if they're out of date]. But for that to be practical, need a way to map versions/fingerprints to the go version. I made [this](https://gist.github.com/dpb587-pivotal/bb3646c517a02438673c4a431590515e) which will work for a while, but it's hacky.

Any ideas (or more interest) on a sustainable way to track and maintain this sort of information?

**Comment by aashah** [comment]
Next time we pull in a new golang release on CI, we'll output information regarding the golang patch in the bump commit. 🤞

Context:

We were uncomfortable giving release authors the ability to run something like `vendor-package 1.13.5` since we wanted people to not have to think about it.

We felt like the question people were really trying to determine was "what version of go is in this thing?!" - so we went with a very low-effort approach. For anyone watching this issue, we'll be looking forward to hearing further feedback on whether this is sufficient!

\- Aakash && @h4xnoodle, BOSH team

**Comment by aashah** [comment]
Following up again for those following the issue, a recent golang version was published so I wanted to share how this is presented: https://github.com/bosh-packages/golang-release/commit/93c192a6beaf75fcb1b416f3f04d0eff0c9374c7
