### ISSUE TITLE
Support compiling with dep.

### ISSUE THREAD

**Issue by kkitai** [bosh-packages/golang-release#15]
My go application is using dep and this release seems to be not supported it. so, bosh can't do "dep ensure" in compile phase.
In workaround. I commit vendor dir into go-app repo. but that is not quite smart.

Would this release has dep pkg?

**Comment by jaresty** [comment]
Hi @kkitai,

This package is meant to be a base install of `golang` and as such it does not include `dep` since `golang` does not include `dep`.  That said, it should be relatively simple to install `dep` as part of your [packaging script](https://bosh.io/docs/packages/#create-a-packaging-script) with `go get -u github.com/golang/dep/cmd/dep` instead of vendoring it in your project. Since is not an intended use case for this release, I'm closing this issue for now.

Best,
Josh

**Comment by kkitai** [comment]
Hi @jaresty .

Thank you for your quick response.
okay.  I will try to make my-app vendoring with only use ```go get``` or "go.mod".
